spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dk"
    username: "root"
    password: "rootroot"
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 3000
      minimum-idle: 10
      maximum-pool-size: 10
      auto-commit: true
      connection-test-query: select 1
